# Site settings
author: LK
title: See Lauren Code
header-img: img/home-bg.png
email: lauren.kohn@soft-adv.com
copyright_name: LK
description: > # this means to ignore newlines until "baseurl:"
  the journey of a thousand miles starts with a single step
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lauren-kohn

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
